name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarScanner
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          ls -l # Verificar el contenido del directorio
          sudo mkdir -p /opt/sonar-scanner
          sudo mv sonar-scanner-5.0.1.3006-linux/* /opt/sonar-scanner/
          ls -l /opt/sonar-scanner # Verificar si se movió correctamente
          sudo chmod +x /opt/sonar-scanner/bin/sonar-scanner
          echo "SONAR_SCANNER_HOME=/opt/sonar-scanner" >> $GITHUB_ENV
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Check if SonarQube is running
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:9000 || echo "SonarQube is not running!"

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=charla-fisc \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}




