name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mkdir -p ~/.sonar
          echo "sonar.organization=tu_organizacion" > ~/.sonar/sonar-project.properties
          echo "sonar.projectKey=tu_proyecto" >> ~/.sonar/sonar-project.properties
          echo "sonar.sources=." >> ~/.sonar/sonar-project.properties
          echo "sonar.host.url=https://sonarcloud.io" >> ~/.sonar/sonar-project.properties
          echo "sonar.token=${SONAR_TOKEN}" >> ~/.sonar/sonar-project.properties

          # Ejecutar el análisis con sonar-scanner
          npx sonar-scanner



