name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarScanner
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          ls -l /opt/sonar-scanner  # Verificar si el directorio se creó correctamente
          sudo chmod +x /opt/sonar-scanner/bin/sonar-scanner
          echo "SONAR_SCANNER_HOME=/opt/sonar-scanner" >> $GITHUB_ENV
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Wait for SonarQube to be available
        run: |
          echo "Verificando disponibilidad de SonarQube..."
          for i in {1..10}; do
            if curl -s --head http://localhost:9000 | grep "200 OK"; then
              echo "✅ SonarQube está disponible."
              exit 0
            fi
            echo "⏳ Esperando que SonarQube inicie... Intento $i/10"
            sleep 10
          done
          echo "❌ SonarQube no está disponible. Verifica que esté ejecutándose en http://localhost:9000"
          exit 1

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=charla-FISC \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true



